### ISSUE TITLE
Meeting 14/11/2019

### ISSUE THREAD

**Issue by kittiu** [ecosoft-odoo/acm#51]
TODO List

- [x] Data as XML :: ข้อมูลที่จำเป็นทุกอย่างควรเป็น XML
- [x] Product Name compute field not working @newtratip 
  * ตอนนี้ไม่สามารถสร้างชื่อ Product แบบอัตโนมัติได้
  * กรณีถ้า user overwrite name เราจะยอมไม๊
- [x] Agreement / Contract Tree / Invoice @newtratip 
  * Product -> Zone = analytic_group_id (required when value type = Rent)
  * Agreement -> add analytic_group_id (required), computed from product line (ค่าเช่า)
  * Agreement create Contract (analytic) ผ่านค่า analytic_group_id (required) มาด้วย
  * @api.constraint > No more than 1 Zone and 1 Product ---> for value type = Rent.
  * Add Zone (analytic_gorup_id) and Product Name in list view, add group by and filter, allow sorting.
- [x] Batch Invoice สำหรับ ค่าน้ำค่าไฟ @kongrattapong 
  * Filter by Zone (analytic_group_id)
  * Use Contract instead of Agreement
  * Create Invoice, with contract (analytic_id)
  * If line subtoal amount == 0, no create invoice
  * Add "ค่าไฟเหมาจ่าย", "Meter Elec 2"
  - [x] Import / Export Excel @kittiu 
  - [x] Reviews by p'Lek, @kongrattapong 
      - Change error ของ negative amount --> OK but please make sure Meter number should not allow input 'negative' also.
      - ช่วยดึง Zone และ Number มาที่ Invoice ด้วย จะได้รู้ว่า เป็นค่าน้ำ ค่าไฟ ของแผงไหน (คาดว่าต้องแสดงใน Report ด้วย) --> ใส่เป็น Text ไว้ที่ Reference/Description
      - Remove "Batch Invoice" from Invoice, buy you can stamp batch invoice number to "Source Document"
      - Invoice สร้างมาจาก Batch ยังไม่มี Analytic Account (contract)
      - ที่หน้า Batch Invoice ถ้า Onchange แล้วเจอว่าในระบบมี Date Range / Zone เดียวกันแล้วในระบบให้แสดงข้อความเตือนว่า "Batch Invoice for this Date Range / Zone already exists".
- [x] Contract -> Create Invoice @kittiu 
  - [x] ระบบไม่ควรยอมให้สร้าง Invoice ที่ไม่มีบรรทัดเลย --> ระบบตอนนี้จะไม่สร้างหากไม่มี invoice line
  - [x] เพิ่ม feature สำหรับ 1 active_id ให้สามารถสร้าง advance invoice ไปข้างหน้าได้
  - [x] สำหรับ multi active_ids ระบบตอนนี้จะไม่ยอกให้เลือก next dates ที่ไม่เหมือนกัน
- [x] Invoice will have 4 Invoice Type ("ค่าเช่า", "ค่าน้ำ-ไฟ", "ค่าสุขา", "ค่าอื่นๆ") (required)
- [ ] Rental Collection Form @kongrattapong 
  * Print form directly from Wizard :: select Zone, เดือน
  * No select agreement, but use view that join product (rent) and agreement
  - [ ] Review by p'Lek @kongrattapong 
    - [ ] Rental Collection Form
      - Add "Date Range" in Wizard
      - Read-only for "Print Date", but user today() to mark "วันที่พิมพ์รายงาน" on the form.
      - บรรทัดสุดท้าย ไม่ต้องเป็นสีเทา
    - [ ] Result from SQL must correct
      - No active agreement -> do not join agreement
      - Many agreements -> join only 1 active agreement only
      - For no agreement product -> Only show product (ล็อก), but don't show category, price.
- [x] ออก Invoice จาก contract ที่ยังไม่เริ่มต้นสัญญา
- [ ] Customer/Supplier Invoice, analytic account should be filtered for appropriate use. I.e., Department @kittiu 
- [ ] Vendor Bill Form QWeb @kongrattapong 
- [ ] Dashboard Reports (by the paper) @newtratip 
- [x] Create a lot of demo data, both agreement and product @newtratip

**Comment by kittiu** [comment]
![image](https://user-images.githubusercontent.com/1973598/68935362-15940880-07cb-11ea-8d84-4f9198d1f813.png)

**Comment by kittiu** [comment]
![image](https://user-images.githubusercontent.com/1973598/68986870-77e61b00-0856-11ea-9162-f4825409e564.png)

**Comment by kittiu** [comment]
![image](https://user-images.githubusercontent.com/1973598/68987067-90efcb80-0858-11ea-9a95-5f98b36ef0bb.png)

**Comment by newtratip** [comment]
I will close this issue because it's long time ago.
